services:
  db:
    profiles:
      - ''
    image: timescale/timescaledb-ha:pg18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - /dev/shm/pgdata:/home/postgres/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    profiles:
      - ''
    image: qdrant/qdrant:gpu-nvidia-latest
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    volumes:
      - /dev/shm/qdrant_storage:/qdrant/storage
      - ./qdrant_config.yaml:/qdrant/config/production.yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  text-embeddings-inference-0:
    profiles:
      - tei
    devices:
      - nvidia.com/gpu=0
    ports:
      - 8080:80
    volumes:
      - ~/tei-volume:/data
    pull_policy: always
    image: ghcr.io/huggingface/text-embeddings-inference:86-1.9
    command: --model-id BAAI/bge-m3 --max-batch-tokens 16384 --dtype float16

  text-embeddings-inference-1:
    profiles:
      - teiv2
    devices:
      - nvidia.com/gpu=1
    ports:
      - 8081:80
    volumes:
      - ~/tei-volume:/data
    pull_policy: always
    image: ghcr.io/huggingface/text-embeddings-inference:86-1.9
    command: --model-id BAAI/bge-m3 --max-batch-tokens 16384 --dtype float16
