CREATE EXTENSION IF NOT EXISTS vectorscale CASCADE;
CREATE EXTENSION IF NOT EXISTS pg_textsearch CASCADE;

CREATE TABLE IF NOT EXISTS articles (
    pmid      INTEGER PRIMARY KEY,
    full_text TEXT
);

CREATE TABLE IF NOT EXISTS ids_per_baseline (
    year INTEGER NOT NULL,
    pmid INTEGER NOT NULL,
    PRIMARY KEY (year, pmid)
);
